### PR TITLE
able to get stored items list in token header after token decoded.

### PR DESCRIPTION
**Pull request by jafaripur**
- Able to get stored items list in token header after token decoded. useful when add custom data to header with `getHeaderToken()` method and want to use in finding user information.
- Refactor code in finding user.

### CODE REVIEW

**Comment by damirka** [comment]
Backward compatibility. Returning 'false' instead of throwing error might break current applications if they update dependencies.

**Comment by damirka** [comment]
What do you think?

**Comment by jafaripur** [comment]
No, returning false just throw unauthorized exception by default and not continue any more.

**Comment by damirka** [comment]
Ok. I'll check your PR in two days.

**Pull request merged**
